name: Rclone Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        curl https://rclone.org/install.sh | sudo bash
    - name: Run Python
      env:
        RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        CMD          : ${{ secrets.CMD }}
        PUSH_URL     : ${{ secrets.PUSH_URL }}
      run: |
        python3 rclone_runner.py "$RCLONE_CONFIG" "$CMD" "$PUSH_URL"